sudo: false
language: emacs-lisp
env:
  - EMACS_BINARY=emacs-26.3-travis
matrix:
  fast_finish: true
before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EMACS_BINARY --use --skip
  - cask
script:
  - emacs --version
  - make test
